### ISSUE TITLE
real time opacity setting

### ISSUE THREAD

**Issue by hot3** [vscode-extension/vscode-background-cover#7]
hello.  

getCss.js
```css
.monaco-workbench{background:none !important;}
```

Users can change opacity in real time with 【 workbench.colorCustomizations 】 for the visibility of code by random image.

```json
"workbench.colorCustomizations": {
    "editor.background": "#00000044", 
    "sideBar.background": "#000000BB",
}
```
"#00000044" → "#00000066" opacity ↑  
"#00000044" → "#00000022" opacity ↓ 

### problems
- the title bar has no color when not active.
- opacity bug in【 panel.background 】

![bug_bg](https://user-images.githubusercontent.com/43977240/51976209-744ff600-24c7-11e9-8457-21ec9f402b5a.png)

### compromise plan

panel.background→RGB + css → opacity

getCss.js
```css
.monaco-workbench{background:none !important;}
.monaco-workbench .panel.integrated-terminal{opacity:0.8}
```

```json
"workbench.colorCustomizations": {
    "editor.background": "#FFFFFF55",
    "sideBar.background": "#FFFFFFCC",
    "panel.background": "#FFFFFF", // ←#FFFFFF66
}
```
![white_bg](https://user-images.githubusercontent.com/43977240/51976246-8a5db680-24c7-11e9-9be1-6ab68c3ee1bd.png)

I will not send you a request this time, but please consider.
